export const US_STATES = {
  CA: { id: "CA", name: "California" },
  GA: { id: "GA", name: "Georgia" },
  TX: { id: "TX", name: "Texas" },
  NC: { id: "NC", name: "North Carolina" },
  FL: { id: "FL", name: "Florida" },
  SC: { id: "SC", name: "South Carolina" },
  NY: { id: "NY", name: "New York" },
  MS: { id: "MS", name: "Mississippi" },
  AZ: { id: "AZ", name: "Arizona" },
  AL: { id: "AL", name: "Alabama" },
  OR: { id: "OR", name: "Oregon" },
  MN: { id: "MN", name: "Minnesota" },
  OK: { id: "OK", name: "Oklahoma" },
  MT: { id: "MT", name: "Montana" },
  NM: { id: "NM", name: "New Mexico" },
  ID: { id: "ID", name: "Idaho" },
  CO: { id: "CO", name: "Colorado" },
  WA: { id: "WA", name: "Washington" },
  WI: { id: "WI", name: "Wisconsin" },
  AR: { id: "AR", name: "Arkansas" },
  TN: { id: "TN", name: "Tennessee" },
  SD: { id: "SD", name: "South Dakota" },
  UT: { id: "UT", name: "Utah" },
  LA: { id: "LA", name: "Louisiana" },
  KY: { id: "KY", name: "Kentucky" },
  NJ: { id: "NJ", name: "New Jersey" },
  PR: { id: "PR", name: "Puerto Rico" },
  WV: { id: "WV", name: "West Virginia" },
  VA: { id: "VA", name: "Virginia" },
  MO: { id: "MO", name: "Missouri" },
  NV: { id: "NV", name: "Nevada" },
  ND: { id: "ND", name: "North Dakota" },
  WY: { id: "WY", name: "Wyoming" },
  ME: { id: "ME", name: "Maine" },
  AK: { id: "AK", name: "Alaska" },
  MI: { id: "MI", name: "Michigan" },
  HI: { id: "HI", name: "Hawaii" },
  PA: { id: "PA", name: "Pennsylvania" },
  NE: { id: "NE", name: "Nebraska" },
  KS: { id: "KS", name: "Kansas" },
  CT: { id: "CT", name: "Connecticut" },
  IA: { id: "IA", name: "Iowa" },
  MD: { id: "MD", name: "Maryland" },
  OH: { id: "OH", name: "Ohio" },
  MA: { id: "MA", name: "Massachusetts" },
  NH: { id: "NH", name: "New Hampshire" },
  IL: { id: "IL", name: "Illinois" },
  IN: { id: "IN", name: "Indiana" },
  RI: { id: "RI", name: "Rhode Island" },
  VT: { id: "VT", name: "Vermont" },
  DE: { id: "DE", name: "Delaware" },
  DC: { id: "DC", name: "District of Columbia" }
};
