
# Server Configuration
server.port=8092

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/events_db
spring.data.mongodb.database=events_db

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8061/eureka/

# Compression Configuration
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=1024

# Default (Local)
python.service.url=http://localhost:8075

# post-service/src/main/resources/application.properties
service.name=post-service-active
service.log-dir=post-service/logs/

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1